import type { Metadata } from "next";
import { Bricolage_Grotesque as Grotesque } from "next/font/google";
import "./globals.css";

const grotesque = Grotesque({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${grotesque.variable} antialiased`}>{children}</body>
    </html>
  );
}
