import { MenuItem } from "@/app/utils/types";

export const todaysSpecials: MenuItem[] = [
  {
    id: "1",
    name: "Truffle Pasta",
    prep: "15 min",
    difficulty: "Medium",
    orders: 45,
    image: "/images/truffle-pasta.jpg",
    description: "Hand-crafted pasta with fresh black truffle and parmesan",
    price: 24,
  },
  {
    id: "2",
    name: "Matcha Cake",
    prep: "30 min",
    difficulty: "Hard",
    orders: 28,
    image: "/images/matcha-cake.jpg",
    description: "Japanese-inspired layered matcha cream cake",
    price: 18,
  },
  {
    id: "3",
    name: "Avocado Toast",
    prep: "10 min",
    difficulty: "Easy",
    orders: 67,
    image: "/images/avocado-toast.jpg",
    description: "Sourdough toast with smashed avocado and poached eggs",
    price: 16,
  },
  {
    id: "4",
    name: "Lobster Risotto",
    prep: "45 min",
    difficulty: "Hard",
    orders: 32,
    image: "/images/lobster-risotto.jpg",
    description: "Creamy arborio rice with fresh lobster and saffron",
    price: 38,
  },
  {
    id: "5",
    name: "Quinoa Bowl",
    prep: "20 min",
    difficulty: "Easy",
    orders: 53,
    image: "/images/quinoa-bowl.jpg",
    description: "Mixed quinoa with roasted vegetables and tahini dressing",
    price: 19,
  },
  {
    id: "6",
    name: "Wagyu Burger",
    prep: "25 min",
    difficulty: "Medium",
    orders: 71,
    image: "/images/wagyu-burger.jpg",
    description:
      "Premium wagyu beef patty with caramelized onions and truffle aioli",
    price: 29,
  },
  {
    id: "7",
    name: "Tiramisu",
    prep: "40 min",
    difficulty: "Medium",
    orders: 39,
    image: "/images/tiramisu.jpg",
    description: "Classic Italian dessert with espresso-soaked ladyfingers",
    price: 14,
  },
  {
    id: "8",
    name: "Poke Bowl",
    prep: "15 min",
    difficulty: "Medium",
    orders: 58,
    image: "/images/poke-bowl.jpg",
    description: "Fresh tuna, rice, avocado, and seaweed with ponzu sauce",
    price: 22,
  },
  {
    id: "9",
    name: "French Onion Soup",
    prep: "35 min",
    difficulty: "Medium",
    orders: 25,
    image: "/images/french-onion-soup.jpg",
    description: "Traditional soup with caramelized onions and gruyere cheese",
    price: 15,
  },
  {
    id: "10",
    name: "Beef Wellington",
    prep: "60 min",
    difficulty: "Hard",
    orders: 18,
    image: "/images/beef-wellington.jpg",
    description: "Tenderloin wrapped in mushroom duxelles and puff pastry",
    price: 45,
  },
  {
    id: "11",
    name: "Vegan Buddha Bowl",
    prep: "25 min",
    difficulty: "Easy",
    orders: 42,
    image: "/images/buddha-bowl.jpg",
    description: "Mixed grains, roasted chickpeas, and seasonal vegetables",
    price: 18,
  },
  {
    id: "12",
    name: "Sea Bass",
    prep: "30 min",
    difficulty: "Hard",
    orders: 34,
    image: "/images/sea-bass.jpg",
    description: "Pan-seared sea bass with lemon butter sauce",
    price: 36,
  },
  {
    id: "13",
    name: "Mushroom Risotto",
    prep: "35 min",
    difficulty: "Medium",
    orders: 47,
    image: "/images/mushroom-risotto.jpg",
    description: "Creamy risotto with wild mushrooms and white wine",
    price: 26,
  },
  {
    id: "14",
    name: "Chocolate Soufflé",
    prep: "25 min",
    difficulty: "Hard",
    orders: 31,
    image: "/images/chocolate-souffle.jpg",
    description: "Warm chocolate soufflé with vanilla ice cream",
    price: 16,
  },
  {
    id: "15",
    name: "Greek Salad",
    prep: "10 min",
    difficulty: "Easy",
    orders: 63,
    image: "/images/greek-salad.jpg",
    description: "Fresh vegetables, feta cheese, and Kalamata olives",
    price: 15,
  },
  {
    id: "16",
    name: "Duck Confit",
    prep: "50 min",
    difficulty: "Hard",
    orders: 22,
    image: "/images/duck-confit.jpg",
    description: "Slow-cooked duck leg with roasted potatoes",
    price: 34,
  },
  {
    id: "17",
    name: "Pad Thai",
    prep: "20 min",
    difficulty: "Medium",
    orders: 56,
    image: "/images/pad-thai.jpg",
    description: "Rice noodles with shrimp, tofu, and traditional sauce",
    price: 21,
  },
  {
    id: "18",
    name: "Crème Brûlée",
    prep: "45 min",
    difficulty: "Medium",
    orders: 37,
    image: "/images/creme-brulee.jpg",
    description: "Classic French vanilla custard with caramelized sugar",
    price: 13,
  },
  {
    id: "19",
    name: "Ramen",
    prep: "30 min",
    difficulty: "Medium",
    orders: 74,
    image: "/images/ramen.jpg",
    description: "Tonkotsu broth with chashu pork and soft-boiled egg",
    price: 19,
  },
  {
    id: "20",
    name: "Beef Tartare",
    prep: "20 min",
    difficulty: "Hard",
    orders: 21,
    image: "/images/beef-tartare.jpg",
    description: "Hand-cut beef with traditional accompaniments",
    price: 28,
  },
  {
    id: "21",
    name: "Shakshuka",
    prep: "25 min",
    difficulty: "Medium",
    orders: 44,
    image: "/images/shakshuka.jpg",
    description: "Eggs poached in spiced tomato sauce with fresh herbs",
    price: 17,
  },
  {
    id: "22",
    name: "Sushi Platter",
    prep: "40 min",
    difficulty: "Hard",
    orders: 36,
    image: "/images/sushi-platter.jpg",
    description: "Assorted nigiri and rolls with wasabi and pickled ginger",
    price: 42,
  },
  {
    id: "23",
    name: "Caesar Salad",
    prep: "15 min",
    difficulty: "Easy",
    orders: 68,
    image: "/images/caesar-salad.jpg",
    description: "Romaine lettuce with house-made dressing and anchovies",
    price: 14,
  },
  {
    id: "24",
    name: "Lamb Chops",
    prep: "35 min",
    difficulty: "Medium",
    orders: 29,
    image: "/images/lamb-chops.jpg",
    description: "Grilled lamb chops with mint sauce and roasted vegetables",
    price: 38,
  },
  {
    id: "25",
    name: "Apple Pie",
    prep: "55 min",
    difficulty: "Medium",
    orders: 33,
    image: "/images/apple-pie.jpg",
    description: "Traditional apple pie with vanilla ice cream",
    price: 12,
  },
  {
    id: "26",
    name: "Seafood Paella",
    prep: "45 min",
    difficulty: "Hard",
    orders: 27,
    image: "/images/seafood-paella.jpg",
    description: "Spanish rice dish with mixed seafood and saffron",
    price: 35,
  },
  {
    id: "27",
    name: "Chicken Tikka Masala",
    prep: "35 min",
    difficulty: "Medium",
    orders: 52,
    image: "/images/tikka-masala.jpg",
    description: "Tandoori chicken in rich tomato-cream sauce",
    price: 23,
  },
  {
    id: "28",
    name: "Caprese Salad",
    prep: "10 min",
    difficulty: "Easy",
    orders: 59,
    image: "/images/caprese-salad.jpg",
    description: "Fresh mozzarella, tomatoes, and basil with balsamic",
    price: 16,
  },
  {
    id: "29",
    name: "Beef Pho",
    prep: "30 min",
    difficulty: "Medium",
    orders: 48,
    image: "/images/beef-pho.jpg",
    description: "Vietnamese noodle soup with beef and fresh herbs",
    price: 20,
  },
  {
    id: "30",
    name: "Mango Sticky Rice",
    prep: "25 min",
    difficulty: "Easy",
    orders: 41,
    image: "/images/mango-sticky-rice.jpg",
    description: "Thai dessert with fresh mango and coconut sauce",
    price: 13,
  },
];
